# -*- coding: utf-8 -*-
"""pandasoperation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_trPRKLy3I2YOTMfLIg1qiElk1G6EgaD
"""

import pandas as pd
import numpy as np

# Creating a broader DataFrame with more varied data
data = {
    'Name': [' john doe ', 'anna smith', 'peter pan', 'lucy li', 'michael johnson'],
    'Age': [28, 24, 35, 40, 22],
    'City': ['new york', 'berlin', 'london', 'new york', 'san francisco'],
    'Email': ['john.doe@example.com', 'anna.smith@berlin.de', 'peter.pan@london.co.uk', 'lucy.li@ny.com', 'michael.johnson@sfrc.com'],
    'Date of Birth': ['1993-05-15', '1997-08-22', '1986-12-10', '1981-03-03', '2000-09-28']
}

# Creating DataFrame
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# 1. Data Cleaning and Standardization
# Remove leading/trailing spaces
df['Name'] = df['Name'].str.strip()

# Capitalize the first letter of each name in 'Name' column
df['Name'] = df['Name'].str.lower().str.capitalize()

# Capitalize the first letter of each word in 'City' column
df['City'] = df['City'].str.title()

# Filling missing 'Age' with the mean age
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Removing duplicates (if any)
df = df.drop_duplicates()

# Renaming columns
df = df.rename(columns={'Name': 'Full Name', 'City': 'Location'})

# 2. Text Column Operations

# a. String Length: Calculate the length of each name
df['Name Length'] = df['Full Name'].str.len()

# b. Extracting First Name from 'Name' (Assuming first name is the first word)
df['First Name'] = df['Full Name'].str.split().str[0]

# c. Extracting Domain from 'Email'
df['Email Domain'] = df['Email'].str.split('@').str[1]

# d. Checking if 'Name' contains "john"
df['Has John'] = df['Full Name'].str.contains('john', case=False)

# e. Replacing "new york" with "NYC" in 'Location' column
df['Location'] = df['Location'].str.replace('New York', 'NYC')

# f. Convert 'Location' names to uppercase
df['Location Upper'] = df['Location'].str.upper()

# g. Extract the first 3 characters from 'Email'
df['Email Prefix'] = df['Email'].str[:3]

# h. Checking if 'Email' ends with ".com"
df['Is .com Email'] = df['Email'].str.endswith('.com')

# i. Concatenate 'First Name' and 'Location' into a new column 'Name & Location'
df['Name & Location'] = df['First Name'] + " from " + df['Location']

# j. Split 'Email' by '.' and take the first part
df['Email User'] = df['Email'].str.split('.').str[0]

# 3. Handle Date Columns (Example: Extracting Year, Month, Day)
df['Date of Birth'] = pd.to_datetime(df['Date of Birth'])
df['Birth Year'] = df['Date of Birth'].dt.year
df['Birth Month'] = df['Date of Birth'].dt.month
df['Birth Day'] = df['Date of Birth'].dt.day

# 4. Display the cleaned DataFrame with text operations applied
print("\nModified DataFrame with Text Operations:\n", df)
====================================
Original DataFrame:
               Name  Age           City                     Email Date of Birth
0        john doe    28       new york      john.doe@example.com    1993-05-15
1       anna smith   24         berlin      anna.smith@berlin.de    1997-08-22
2        peter pan   35         london    peter.pan@london.co.uk    1986-12-10
3          lucy li   40       new york            lucy.li@ny.com    1981-03-03
4  michael johnson   22  san francisco  michael.johnson@sfrc.com    2000-09-28

Modified DataFrame with Text Operations:
          Full Name  Age       Location                     Email  \
0         John doe   28            NYC      john.doe@example.com   
1       Anna smith   24         Berlin      anna.smith@berlin.de   
2        Peter pan   35         London    peter.pan@london.co.uk   
3          Lucy li   40            NYC            lucy.li@ny.com   
4  Michael johnson   22  San Francisco  michael.johnson@sfrc.com   

  Date of Birth  Name Length First Name  Email Domain  Has John  \
0    1993-05-15            8       John   example.com      True   
1    1997-08-22           10       Anna     berlin.de     False   
2    1986-12-10            9      Peter  london.co.uk     False   
3    1981-03-03            7       Lucy        ny.com     False   
4    2000-09-28           15    Michael      sfrc.com      True   

  Location Upper Email Prefix  Is .com Email             Name & Location  \
0            NYC          joh           True               John from NYC   
1         BERLIN          ann          False            Anna from Berlin   
2         LONDON          pet          False           Peter from London   
3            NYC          luc           True               Lucy from NYC   
4  SAN FRANCISCO          mic           True  Michael from San Francisco   

  Email User  Birth Year  Birth Month  Birth Day  
0       john        1993            5         15  
1       anna        1997            8         22  
2      peter        1986           12         10  
3       lucy        1981            3          3  
4    michael        2000            9         28  
