# -*- coding: utf-8 -*-
"""ArrayandMatrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_trPRKLy3I2YOTMfLIg1qiElk1G6EgaD
"""

import numpy as np

# 1. Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# 2. Array operations
arr_add = arr + 5  # Adding 5 to each element
arr_mul = arr * 2  # Multiplying each element by 2
print("\nArray after addition:", arr_add)
print("Array after multiplication:", arr_mul)

# 3. Array statistics
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

# 4. Creating a 2D array (Matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatrix:\n", matrix)

# 5. Transpose of a matrix
matrix_transpose = matrix.T
print("\nTranspose of the matrix:\n", matrix_transpose)

# 6. Matrix multiplication (Dot product)
matrix2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])  # Identity matrix
matrix_mult = np.dot(matrix, matrix2)
print("\nMatrix multiplication (Dot product):\n", matrix_mult)

# 7. Reshaping a matrix
reshaped_matrix = matrix.reshape(1, 9)
print("\nReshaped matrix:\n", reshaped_matrix)

# 8. Element-wise operations
arr_squared = np.square(arr)  # Squaring each element
print("\nArray after squaring:", arr_squared)

# 9. Finding max, min, and index of max in an array
max_value = np.max(arr)
min_value = np.min(arr)
max_index = np.argmax(arr)
print("\nMax value:", max_value)
print("Min value:", min_value)
print("Index of max value:", max_index)

# 10. Indexing and slicing
sliced_arr = arr[1:4]  # Slicing the array from index 1 to 3
print("\nSliced Array (index 1 to 3):", sliced_arr)

# 11. Random number generation
random_arr = np.random.randint(1, 100, size=5)  # Random integers between 1 and 100
print("\nRandom array:", random_arr)

# 12. Create an array of ones and zeros
ones_array = np.ones(5)  # Array of ones
zeros_array = np.zeros(5)  # Array of zeros
print("\nArray of ones:", ones_array)
print("Array of zeros:", zeros_array)