# -*- coding: utf-8 -*-
"""normalize_standardize_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_trPRKLy3I2YOTMfLIg1qiElk1G6EgaD
"""

import numpy as np

# Function for normalization (min-max scaling)
def normalize_data(data):
    min_value = np.min(data, axis=0)
    max_value = np.max(data, axis=0)
    normalized_data = (data - min_value) / (max_value - min_value)
    return normalized_data

# Function for standardization (z-score scaling)
def standardize_data(data):
    mean_value = np.mean(data, axis=0)
    std_dev = np.std(data, axis=0)
    standardized_data = (data - mean_value) / std_dev
    return standardized_data

# Main function to run the project
def data_normalization_standardization():
    # Example dataset (rows are samples, columns are features)
    # Columns: age, salary, years of experience
    data = np.array([
        [25, 50000, 2],
        [30, 60000, 4],
        [35, 70000, 6],
        [40, 80000, 8],
        [45, 90000, 10]
    ])

    print("Original Data (Age, Salary, Experience):\n", data)

    normalized_data = normalize_data(data)
    print("\nNormalized Data (Min-Max Scaling):\n", normalized_data)

    standardized_data = standardize_data(data)
    print("\nStandardized Data (Z-Score Scaling):\n", standardized_data)

if __name__ == "__main__":
    data_normalization_standardization()